config/routes.rb
Worldcup::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :answers
  resources :bets

  devise_for :users

  root 'static_pages#home'
  get 'play' => 'users'
  get 'ranking'=> 'users#index'
  get 'next_bets' => 'bets#next_bets'
  get 'all_bets' =>'bets#all_bets'
  get 'results'=> 'matches#results'
  get 'bases' => 'static_pages#bases'

  resources :users,:constraints => {:id => /\d+/}, :only => [:show,:edit]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end
  def bases

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def home

  end
end

app/views/static_pages/bases.erb
<div class="row clearfix"  style=" padding-left: 10px; padding-right: 10px;">
  <div class="col-md-12 column">
  <h1>
      BASES POLLA COPA CENTENARIO  2016              
  </h1>
    <h2>
      1.- De los Participantes:
    </h2>
    <p>
      Pueden participar de esta polla todos aquellos que sean aprobador por el comité organizador de la polla, todos los que participaron de la gran Polla Mundial Brasil 2014 y la Polla Copa America 2015, se entienden como aprobados por el comité. Además de esto, para poder realizar cualquier apuesta es requerido haber depositado la cuota de participación, 10.000 pesos, a la cuenta bancaria siguiente:
    </p>
    <p>
      Mauricio Alejandro Vera Pino
    </p>
    <p>
      17.090.236-k
    </p>
    <p>
      mverapino@gmail.com 
    </p>
    <p>
      Banco Santander
    </p>
    <p>
      Cuenta Vista
    </p>
    <p>
      7016429060
    </p>
    <h2>
      2.- De las Apuestas
    </h2>
    <p>
      El sistema de apuestas está basando en puntos, cada predicción acertada entrega un número determinado de puntos, finalizada la copa aquel participante que tenga mayor cantidad de puntos será el ganador de la polla. Las apuestas están divididas en dos grupos, apuestas partido a partido llamadas “apuesta exacta” y apuestas previas llamadas “apuestas bono”. A continuación se muestra el detalle para cada apuesta:
    </p>
    <h3>Apuesta Exacta:</h3>
    <p>
      Esta apuesta debe realizarse para cada uno de los 32 partidos de la copa, se debe apostar al resultado exacto de estos y la apuesta debe estar realizada antes del comienzo de cada partido, si un partido comienza y no se ha realizado ninguna apuesta este quedara sin apostar. Para las apuestas exactas los puntajes son los siguientes:
    </p>
    <ul>
    <li>4 pts cuando se acierta resultado exacto del partido.</li>
    <li>2 pts cuando se acierta ganador o empate.</li>
    </ul>

    <h3>Apuestas Bono:</3>
    <p>
      Estas son un grupo de apuestas a resultados generales de selecciones, resultados de los grupos y premios individuales a jugadores entre otros, en total son 14 predicciones diferentes que deben realizarse antes de que empiece el primer partido de la copa, 6 de junio de 2016 a las 12:00 hrs. Cualquier apuesta bono que quede sin realizarse pasado este plazo, quedara vacía y no entregara puntaje alguno, los puntajes y apuestas son los siguientes:
    </p>
    <ul>
    <li>Campeón, subcampeón, tercer y cuarto lugar entregan 6 pts cada una.</li>
    <li>Goleador, mejor jugador entregan 8 pts cada una. El mejor jugador será definido por FIFA al finalizado el campeonato.</li>
    <li>El equipo revelación entrega 6 pts, será el que quede en más alto puesto al finalizado el campeonato, determinado por FIFA, entre los siguientes equipos: Ecuador, Bolivia, Paraguay, Jamaica, Perú, Venezuela, Haiti, Panama y Costa Rica.</li>
    <li>Desempeño de Chile en la copa entrega 8 pts. Este puede ser: eliminado en primera ronda, cuartos de final, cuarto, tercero, subcampeón y campeón.</li>
    <li>Primer y segundo lugar de cada grupo entregan 2 pts cada uno. Se considera acierto cuando el resultado del grupo se da en el orden apostado, es posible poner un mismo equipo como primero y segundo de su grupo.</li>
    </ul>


    <h2>
      2.- De los premios
    </h2>
    <p>
      La Polla Copa Centenario 2016 entregará 3 premios, al primer lugar, segundo lugar y el último lugar,  todos estos definidos por la suma de puntos obtenidos al finalizar el torneo. En caso de existir un empate el ganador se va a definir por la persona que tenga mayor cantidad de aciertos simples en las apuestas exactas, en caso de mantenerse el empate el ganador se definirá con el que tenga correcto las siguientes apuestas bono; desempeño de Chile, campeón y subcampeón. En caso de persistir el empate, se definirá lanzando una moneda al mejor de 3. 
    </p>
    <p>Los premios serán los siguientes:</p>
    <ul>
    <li>Ganador: se llevará todo el dinero recolectado antes de empezar el campeonato menos 10.000 pesos, correspondientes a una cuota de participación. Además de esto podrá usar el título de “el que más sabe” y en el caso de Cristian Dumay, podrá usar el título de “bi-campeón”.</li>
    <li>Segundo lugar: se llevara como premio su cuota de participación, es decir 10.000 pesos.</li>
    <li>Último lugar: tendrá la obligación de poner su casa como sede para el asado de cierre de la polla Copa Centenario 2016, en donde se espera que el ganador se ponga con el asado o al menos parte de este.</li>
    </ul>

<p><bold>COMITÉ ORGANIZADOR POLLA COPA CENTENRIO 2016.</bold></p>
  </div>
</div>

app/views/static_pages/home.erb
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          Hola
        </h1>
        <p>
            Esta va a ser la aplicacion que vamos a ocupar para polla de la Copa Centenario 2016
        </p>
        <p>
          <% if user_signed_in? %>
            <%= link_to 'Jugar', play_path, class: 'btn btn-primary btn-large'%>
          <% else %>
            
            <!-- <a class="btn btn-primary btn-large" href="<%= new_user_session_path %>">Ingresa</a> -->
              <%= link_to 'Ingresa', new_user_session_path, class: 'btn btn-primary btn-large'%>
            
          <% end %>
        </p>
      </div>
    </div>
  </div>
<div class="row clearfix" style=" padding-left: 10px; padding-right: 10px;">
  <div class="col-md-6 column" >
    <h2>
      Bases
    </h2>
    <p>
      Aqui se puede ver las bases para la polla de la copa centenario 2016
    </p>
    <p>
      <%= link_to 'Ver Bases', bases_path, class: 'btn'%>

    </p>
  </div>
  <div class="col-md-6 column" >
    <h2>
      Dumay Campeón
    </h2>
    <p>
      Dumay fue el campeon de la ultima polla. Todavia esperamos a que se ponga la casa pal asado.
    </p>
    <p>
      
    </p>
  </div>
</div>
<div class="row clearfix">
  <div class="col-md-4 column">
  </div>
  <div class="col-md-4 column">
  </div>
  <div class="col-md-4 column">
  </div>
</div>