config/routes.rb
Worldcup::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :answers
  resources :bets

  devise_for :users

  root 'static_pages#home'
  get 'play' => 'users'
  get 'ranking'=> 'users#index'
  get 'next_bets' => 'bets#next_bets'
  get 'all_bets' =>'bets#all_bets'
  get 'results'=> 'matches#results'
  get 'bases' => 'static_pages#bases'

  resources :users,:constraints => {:id => /\d+/}, :only => [:show,:edit]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polla Copa America</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<div class="fluid-container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <nav class="navbar navbar-default" role="navigation">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
          <%= link_to root_path ,class:'navbar-brand' do %>
              <%=  image_tag 'logo.jpg' %>
          <% end %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="<%= is_active('play')%>">
              <%= link_to 'JUGAR', play_path  %>
            </li>
            <li class="<%= is_active('ranking')%>">
              <%= link_to 'Ranking',ranking_path %>
            </li>
            <li class="<%= is_active('next_bets')%>">
              <%= link_to 'Proximas Apuestas',next_bets_path %>
            </li>
            <li class="<%= is_active('all_bets')%>">
              <%= link_to 'Todas las apuestas',all_bets_path %>
            </li>
            <li class="<%= is_active('results')%>">
              <%= link_to 'Resultados',results_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Mi Perfil', user_path(current_user) %>
                </li>
                <li>
                  <%= link_to 'Editar Perfil', edit_user_registration_path %>
                </li>
                <li class="divider">
                </li>
                <li>
                  <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
            <% else %>
                <li>
                  <%= link_to 'Ingresar', new_user_session_path%>
                </li>
            <% end %>
          </ul>
        </div>

      </nav>
    </div>
  </div>
  <%= yield %>
</div>


</body>
</html>